In [1]:
import numpy as np

In [32]:
l1 = [3,4,5,6,7]
# l1 = [6,8,10,12,14]

In [33]:
sum(l1)

25

In [6]:
arr = np.array(l1)
print("Array is :",arr)

Array is : [3 4 5 6 7]


In [8]:
arr * 2

array([ 6,  8, 10, 12, 14])

In [10]:
arr / 2

array([1.5, 2. , 2.5, 3. , 3.5])

In [12]:
arr ** 2

array([ 9, 16, 25, 36, 49], dtype=int32)

In [14]:
arr // 2

array([1, 2, 2, 3, 3], dtype=int32)

In [17]:
arr % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [18]:
arr % 3

array([0, 1, 2, 0, 1], dtype=int32)

In [20]:
arr = arr ** 3
result = arr.tolist()
print(result)

[19683, 262144, 1953125, 10077696, 40353607]


In [22]:
a1 = np.array([10,20,30,40])
a2 = np.array([5,4,2,5])
a1 + a2

array([15, 24, 32, 45])

In [25]:
a1 = np.array([10,20,30,40])
a2 = np.array([5,4,2,5])
a1 + a2

array([15, 24, 32, 45])

In [27]:
a1 = np.array([10,20,30,40])
a2 = np.array([5,4,2,5])
a1 * a2

array([ 50,  80,  60, 200])

In [29]:
np.add(a1,a2)

array([15, 24, 32, 45])

In [31]:
np.sum(a1)

100

In [34]:
np.sum(a1)

100

In [36]:
a1 = np.array([[10,20],[30,40]])
a2 = np.array([[5,4],[2,5]])

In [38]:
print('Array1 is \n',a1)
print("Array2 is \n",a2)

Array1 is 
 [[10 20]
 [30 40]]
Array2 is 
 [[5 4]
 [2 5]]


### Matrix Addition

In [40]:
np.add(a1,a2)

array([[15, 24],
       [32, 45]])

### Matrix Multiplication

In [41]:
print('Array1 is \n',a1)
print("Array2 is \n",a2)

Array1 is 
 [[10 20]
 [30 40]]
Array2 is 
 [[5 4]
 [2 5]]


In [43]:
np.multiply(a1,a2)

array([[ 50,  80],
       [ 60, 200]])

### Matrix Dot product

In [45]:
matrix1 = np.array([[2,3],[4,6]])
matrix2 = np.array([[5,4],[2,5]])

print("Matrix 1 is :\n",matrix1)
print("Matrix 2 is :\n",matrix2)

Matrix 1 is :
 [[2 3]
 [4 6]]
Matrix 2 is :
 [[5 4]
 [2 5]]


In [48]:
np.dot(matrix1,matrix2)

# 2*5 + 3*2    2*4 + 3*5
# 4*5 + 6*2    4*4 + 6*5

array([[16, 23],
       [32, 46]])

In [52]:
matrix1 = np.array([[2,3],[4,6],[3,4]])  # 3*2
matrix2 = np.array([[5,4],[2,5]])   # 2 * 

print("Matrix 1 is :\n",matrix1)
print("Matrix 2 is :\n",matrix2)

Matrix 1 is :
 [[2 3]
 [4 6]
 [3 4]]
Matrix 2 is :
 [[5 4]
 [2 5]]


In [53]:
np.dot(matrix1,matrix2)  

array([[16, 23],
       [32, 46],
       [23, 32]])

In [ ]:
2 * 4 
4 * 5
2*5

3*3   2*3