# Numpy Functions

In [1]:
# 1. np.reshape

# 2. np.zeros()

In [3]:
import numpy as np

In [5]:
arr = np.zeros(5)
arr


array([0., 0., 0., 0., 0.])

In [7]:
arr = np.zeros(5,dtype = 'int')
arr

array([0, 0, 0, 0, 0])

In [ ]:
1000 class1
1000 class2


In [16]:
np.zeros(100,dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
arr0 = np.zeros([2,3],dtype = 'int')  # 2 * 3
arr0

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
arr0 = np.zeros([4,5],dtype = 'int')  # 2 * 3
arr0

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 3. np.ones()

In [13]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
arr1 = np.ones(10,dtype = 'int')
arr1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
arr0 = np.ones([2,3],dtype = 'int')  # 2 * 3
arr0

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
arr0 = np.ones([5,6],dtype = 'int')  # 2 * 3
arr0.shape

(5, 6)

In [25]:
import pandas as pd

In [28]:
df = pd.DataFrame(arr0)
df

0  1  2  3  4  5
0  1  1  1  1  1  1
1  1  1  1  1  1  1
2  1  1  1  1  1  1
3  1  1  1  1  1  1
4  1  1  1  1  1  1

# 4. arange()

In [30]:
array1 = np.arange(1,11)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
array1 = np.arange(10,20)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
array1 = np.arange(10,21,1)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
array1 = np.arange(10,21,2)
array1

array([10, 12, 14, 16, 18, 20])

In [40]:
array1 = np.arange(21,10,-1)
array1

array([21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [42]:
array1 = np.arange(21,10)
array1

array([], dtype=int32)

In [46]:
array1 = np.arange(10,30)
array1.shape

(20,)

In [50]:
array1.reshape([5,4])

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [51]:
array1.reshape([2,10])

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# 5. linspace()

In [56]:
array2 = np.linspace(1,50)
array2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [58]:
array2 = np.linspace(1,50, num = 50)
array2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [81]:
array2 = np.linspace(1,50, num = 10,retstep = True)
array2

(array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
        28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ]),
 5.444444444444445)

In [83]:
array2 = np.linspace(1,10, num = 10,retstep = True)
array2

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [84]:
array2 = np.linspace(1,10, num = 5,retstep = True)
array2

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [85]:
array2 = np.linspace(1,50, num = 20,retstep = True)
array2

(array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
        13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
        26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
        39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ]),
 2.5789473684210527)

In [86]:
49/19

2.5789473684210527

In [68]:
array2 = np.linspace(100,500, num = 20,retstep = True)
array2

(array([100.        , 121.05263158, 142.10526316, 163.15789474,
        184.21052632, 205.26315789, 226.31578947, 247.36842105,
        268.42105263, 289.47368421, 310.52631579, 331.57894737,
        352.63157895, 373.68421053, 394.73684211, 415.78947368,
        436.84210526, 457.89473684, 478.94736842, 500.        ]),
 21.05263157894737)

In [69]:
array2 = np.linspace(1,500, num = 20,retstep = True)
array2

(array([  1.        ,  27.26315789,  53.52631579,  79.78947368,
        106.05263158, 132.31578947, 158.57894737, 184.84210526,
        211.10526316, 237.36842105, 263.63157895, 289.89473684,
        316.15789474, 342.42105263, 368.68421053, 394.94736842,
        421.21052632, 447.47368421, 473.73684211, 500.        ]),
 26.263157894736842)

In [71]:
dict1 = {'zeros':np.zeros(10),
        'Ones':np.ones(10),
        'Arange':np.arange(10,20),
        "LinSpace":np.linspace(100,200,num = 10)}
print(dict1)

{'zeros': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'Ones': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 'Arange': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), 'LinSpace': array([100.        , 111.11111111, 122.22222222, 133.33333333,
       144.44444444, 155.55555556, 166.66666667, 177.77777778,
       188.88888889, 200.        ])}


In [74]:
df = pd.DataFrame(dict1)
df

zeros  Ones  Arange    LinSpace
0    0.0   1.0      10  100.000000
1    0.0   1.0      11  111.111111
2    0.0   1.0      12  122.222222
3    0.0   1.0      13  133.333333
4    0.0   1.0      14  144.444444
5    0.0   1.0      15  155.555556
6    0.0   1.0      16  166.666667
7    0.0   1.0      17  177.777778
8    0.0   1.0      18  188.888889
9    0.0   1.0      19  200.000000

In [87]:
df['List1'] = [2,3,4,5,6,np.nan,2,3,4,5]
df

zeros  Ones  Arange    LinSpace  List1
0    0.0   1.0      10  100.000000    2.0
1    0.0   1.0      11  111.111111    3.0
2    0.0   1.0      12  122.222222    4.0
3    0.0   1.0      13  133.333333    5.0
4    0.0   1.0      14  144.444444    6.0
5    0.0   1.0      15  155.555556    NaN
6    0.0   1.0      16  166.666667    2.0
7    0.0   1.0      17  177.777778    3.0
8    0.0   1.0      18  188.888889    4.0
9    0.0   1.0      19  200.000000    5.0

# 6. eye

In [89]:
np.eye(3,dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [91]:
np.eye(5,dtype = 'int')  # Identity Matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [93]:
np.eye(3,4,dtype = 'int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [95]:
np.eye(3,10,dtype = 'int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

# 7. Identity()

In [97]:
np.identity(3,dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [100]:
np.identity(4,dtype = 'int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [102]:
np.eye(4,dtype = 'int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# 8. random()

In [ ]:
Used for generating random numbers
1. rand()
2. randint()
3. randn()
4. randf()

## 8.1 random.rand()

In [104]:
arr1 = np.random.rand(5)
arr1

array([0.3526005 , 0.10299015, 0.89112894, 0.73509703, 0.80664128])

In [114]:
arr1 = np.random.rand(10)
arr1

array([0.57707453, 0.26041674, 0.85307086, 0.12325736, 0.58029799,
       0.03025585, 0.22337377, 0.35379858, 0.15640777, 0.39646609])

In [116]:
arr1 = np.random.rand(4,5)
arr1

array([[0.45312982, 0.33991502, 0.8008794 , 0.75053189, 0.43113924],
       [0.469681  , 0.89906   , 0.77081947, 0.55638148, 0.54567417],
       [0.48539954, 0.09464577, 0.19854768, 0.81397063, 0.5357663 ],
       [0.99636983, 0.22966705, 0.19839446, 0.26814142, 0.81118775]])

In [118]:
arr1 = np.random.rand(2,3)
arr1

array([[0.95575172, 0.08853534, 0.33659815],
       [0.8612003 , 0.0419216 , 0.55526711]])

## 8.2 random.randint()

In [122]:
arr = np.random.randint(1,20,size = 20)
arr

array([ 2,  4,  3,  1, 12, 18,  6,  7, 17, 16, 13,  8,  7, 14, 15, 12,  4,
        1,  5, 17])

In [124]:
arr = np.random.randint(1,20,size = 10)
arr

array([ 1, 17,  1, 10, 19, 12, 10, 10, 13, 12])

In [134]:
arr = np.random.randint(10,100,size = 10)
arr

array([17, 87, 37, 14, 89, 88, 20, 39, 69, 52])

In [137]:
arr = np.random.randint(0,100,size = 10)
arr

array([10, 25, 59, 53, 39, 88, 19, 27, 92, 97])

In [144]:
arr = np.random.randint(0,100,size = 20)
arr

array([12, 79, 92, 21, 63, 11, 19, 64, 54, 48, 64, 48, 29, 84, 86, 12,  3,
       51, 14, 21])

In [149]:
arr = np.random.randint(100,200,size = 20)
arr.reshape(4,5)

array([[114, 176, 159, 184, 179],
       [132, 107, 125, 141, 175],
       [100, 104, 115, 163, 140],
       [191, 177, 119, 171, 179]])

## 8.4 random.randn

In [151]:
arr = np.random.randn(5)
arr

array([-0.04372591,  0.25961092,  1.15749813,  0.41984125,  0.54671544])

In [157]:
arr = np.random.randn(6)
arr

array([ 0.27788767,  0.10299908,  0.0399048 , -1.36724277, -0.2183563 ,
       -0.09484913])

## 8.5 random.ranf()

In [163]:
arr = np.random.ranf((4,))
arr

array([0.02684291, 0.90733577, 0.74560569, 0.90272884])

In [164]:
arr = np.random.ranf((5,))
arr

array([0.87686171, 0.24558749, 0.27366021, 0.231759  , 0.98871953])

In [166]:
# randint
# linspace
# arange

# 9. sort

In [167]:
arr = np.random.randint(10,40,size = 10)
arr

array([25, 12, 15, 18, 34, 22, 10, 25, 28, 31])

In [169]:
np.sort(arr)

array([10, 12, 15, 18, 22, 25, 25, 28, 31, 34])

In [ ]:
# Axis = 0  >> Rows
# Axis = 1  >> Column

In [174]:
dict1 = {'zeros':np.zeros(10),
        'Ones':np.ones(10),
        'Arange':np.arange(10,20),
        "LinSpace":np.linspace(100,200,num = 10),
        "RandInt":np.random.randint(10,40,size = 10),
        'RandNormal':np.random.randn(10)}
print(dict1)

{'zeros': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'Ones': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 'Arange': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), 'LinSpace': array([100.        , 111.11111111, 122.22222222, 133.33333333,
       144.44444444, 155.55555556, 166.66666667, 177.77777778,
       188.88888889, 200.        ]), 'RandInt': array([23, 31, 18, 34, 21, 16, 15, 23, 23, 35]), 'RandNormal': array([-0.32496639, -0.01820217, -2.92672803,  1.3471082 ,  1.92020756,
       -1.78399696, -1.49410367, -0.47312967,  1.38503787,  0.5733818 ])}


In [176]:
df = pd.DataFrame(dict1)
df

zeros  Ones  Arange    LinSpace  RandInt  RandNormal
0    0.0   1.0      10  100.000000       23   -0.324966
1    0.0   1.0      11  111.111111       31   -0.018202
2    0.0   1.0      12  122.222222       18   -2.926728
3    0.0   1.0      13  133.333333       34    1.347108
4    0.0   1.0      14  144.444444       21    1.920208
5    0.0   1.0      15  155.555556       16   -1.783997
6    0.0   1.0      16  166.666667       15   -1.494104
7    0.0   1.0      17  177.777778       23   -0.473130
8    0.0   1.0      18  188.888889       23    1.385038
9    0.0   1.0      19  200.000000       35    0.573382

In [181]:
df.sort_values(['RandInt','RandNormal'])

zeros  Ones  Arange    LinSpace  RandInt  RandNormal
6    0.0   1.0      16  166.666667       15   -1.494104
5    0.0   1.0      15  155.555556       16   -1.783997
2    0.0   1.0      12  122.222222       18   -2.926728
4    0.0   1.0      14  144.444444       21    1.920208
7    0.0   1.0      17  177.777778       23   -0.473130
0    0.0   1.0      10  100.000000       23   -0.324966
8    0.0   1.0      18  188.888889       23    1.385038
1    0.0   1.0      11  111.111111       31   -0.018202
3    0.0   1.0      13  133.333333       34    1.347108
9    0.0   1.0      19  200.000000       35    0.573382

In [180]:
df.sort_index(axis = 1)

Arange    LinSpace  Ones  RandInt  RandNormal  zeros
0      10  100.000000   1.0       23   -0.324966    0.0
1      11  111.111111   1.0       31   -0.018202    0.0
2      12  122.222222   1.0       18   -2.926728    0.0
3      13  133.333333   1.0       34    1.347108    0.0
4      14  144.444444   1.0       21    1.920208    0.0
5      15  155.555556   1.0       16   -1.783997    0.0
6      16  166.666667   1.0       15   -1.494104    0.0
7      17  177.777778   1.0       23   -0.473130    0.0
8      18  188.888889   1.0       23    1.385038    0.0
9      19  200.000000   1.0       35    0.573382    0.0