# NumPy

In [ ]:
Application :
    1. Linear Algebra
    2. Statistics(mean,median,std,var)
    3. Probability
    4. Image Processing
    5. Trignometric (sin,cos,tan,etc)
    6. Random Number generation
    7. Logarithmic    

In [ ]:
It is collection Homegeneous data types
ndarray >> n dimensional array (0D,1D,2D,  nD)
Numpy array are faster than list
Numpy is written in Python, C , C++
C is faster than Python Language
Array can be created using list,tuple

In [2]:
import numpy as np

In [6]:
# np.array(list,tuple)

arr1 = np.array([2,3,4,5,2]) # lsit
arr1
type(arr1)
# ndarray 

numpy.ndarray

In [10]:

arr1 = np.array((5,6,7,8)) # Tuple
arr1, type(arr1)


(array([5, 6, 7, 8]), numpy.ndarray)

In [12]:
l1 = [3,4,5,6,7]
array = np.array(l1)
array

array([3, 4, 5, 6, 7])

In [4]:
import numpy as np
l1 = [3.0,4.0,5.5,6.0,7]
array = np.array(l1)
array

array([3. , 4. , 5.5, 6. , 7. ])

In [17]:
l1 = [3,4,5,6,7.5, 4+5j]
array = np.array(l1)
array

array([3. +0.j, 4. +0.j, 5. +0.j, 6. +0.j, 7.5+0.j, 4. +5.j])

In [15]:
l1 = [3,4,5,6,'a']
array = np.array(l1)
array

array(['3', '4', '5', '6', 'a'], dtype='<U11')

# Change the data Type

In [21]:
array = np.array([3,4,5,7],dtype = 'int')
array

array([3, 4, 5, 7])

In [24]:
array = np.array([3,4,5,7],dtype = 'float')
array

array([3., 4., 5., 7.])

In [33]:
array = np.array([3,4,5,7],dtype = 'complex')
array

array([3.+0.j, 4.+0.j, 5.+0.j, 7.+0.j])

In [35]:
array = np.array([3,4,5.6,3.7],dtype = 'int')
array

array([3, 4, 5, 3])

In [5]:
3.

3.0

In [28]:
array = np.array([3,4,5,7 + 5j],dtype = 'complex')
array

array([3.+0.j, 4.+0.j, 5.+0.j, 7.+5.j])

In [30]:
array = np.array([3,4,5,7 + 5j],dtype = 'float')
array

TypeError: can't convert complex to float

In [36]:
array = np.array([3,4,5,7 + 5j],dtype = 'int')
array

TypeError: can't convert complex to int

In [38]:
array = np.array([3,4,5,7 ],dtype = 'object')
array

array([3, 4, 5, 7], dtype=object)

# Dimensions in array

## 1. 0-D

In [42]:
arr0 = np.array(45)
arr0.ndim
print('Number of dimensions are : ',arr0.ndim)

Number of dimensions are :  0


In [44]:
arr0 = np.array(4.5)
arr0.ndim
print('Number of dimensions are : ',arr0.ndim)

Number of dimensions are :  0


## 2. 1-D

In [47]:
arr1 = np.array([3,4,5,6])
print('Number of dimensions are : ',arr1.ndim)

Number of dimensions are :  1


In [6]:
arr1 = np.array([[[3,4.5,6.7,10,20]]])
print('Number of dimensions are : ',arr1.ndim)

Number of dimensions are :  3


In [50]:
arr1 = np.array([3])
print('Number of dimensions are : ',arr1.ndim)

Number of dimensions are :  1


In [87]:
arr1 = np.array([3,5])
print('Array is :',arr1)
print('Number of dimensions are : ',arr1.ndim)

Array is : [3 5]
Number of dimensions are :  1


In [89]:
arr1 = np.array([3,5,6])
print('Array is :',arr1)
print('Number of dimensions are : ',arr1.ndim)
print("Shape of an array is :",arr1.shape)

Array is : [3 5 6]
Number of dimensions are :  1
Shape of an array is : (3,)


## 3. 2-D array

In [90]:
arr2 = np.array([[2,3],[5,6],[7,8]])
print('Array is :\n',arr2)
print('Number of dimensions are : ',arr2.ndim)
print("Shape of an array is :",arr2.shape)
# (3,2) >> 3 1D array and 2items in 1D

Array is :
 [[2 3]
 [5 6]
 [7 8]]
Number of dimensions are :  2
Shape of an array is : (3, 2)


In [58]:
arr2 = np.array([[2,3]])
print('Array is :\n',arr2)
print('Number of dimensions are : ',arr2.ndim)

Array is :
 [[2 3]]
Number of dimensions are :  2


In [59]:
arr2 = np.array([[2,3]])
print('Array is :\n',arr2)
print('Number of dimensions are : ',arr2.ndim)

Array is :
 [[2 3]]
Number of dimensions are :  2


In [62]:
arr2 = np.array([[2,3],[4,5]])
print('Array is :\n',arr2)
print('Number of dimensions are : ',arr2.ndim)

Array is :
 [[2 3]
 [4 5]]
Number of dimensions are :  2


In [67]:
arr2 = np.array(([2,3],[4,5]))
print('Array is :\n',arr2)
print('Number of dimensions are : ',arr2.ndim)

Array is :
 [[2 3]
 [4 5]]
Number of dimensions are :  2


In [69]:
arr2 = np.array(([2,3,4,5]))
print('Array is :\n',arr2)
print('Number of dimensions are : ',arr2.ndim)

Array is :
 [2 3 4 5]
Number of dimensions are :  1


In [71]:
([2,3,4,5])

[2, 3, 4, 5]

In [83]:
arr2 = np.array([[2,3,4,5]])
print('Array is :\n',arr2)
print('Number of dimensions are : ',arr2.ndim)

Array is :
 [[2 3 4 5]]
Number of dimensions are :  2


In [84]:
arr2 = np.array([[2,3,4,5]])  # Multiple 1 D array
print('Array is :\n',arr2)
print('Number of dimensions are : ',arr2.ndim)

Array is :
 [[2 3 4 5]]
Number of dimensions are :  2


In [85]:
arr2 = np.array([[2,3,4,5],[2,3,4,5],[2,3,4,5],[2,3,4,5]])  # Multiple 1 D array
print('Array is :\n',arr2)
print('Number of dimensions are : ',arr2.ndim)

Array is :
 [[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]
Number of dimensions are :  2


## 3-D array

In [73]:
arr3 = np.array([[[2,3,4,5]]])
print('Array is :\n',arr3)
print('Number of dimensions are : ',arr3.ndim)

Array is :
 [[[2 3 4 5]]]
Number of dimensions are :  3


In [91]:
arr3 = np.array([[[2,3],[3,4],[5,6]]])
print('Array is :\n',arr3)
print('Number of dimensions are : ',arr3.ndim)
print("Shape of an array is :",arr3.shape)
# (1,3,2)
# 1 >> number of 2D
# 3 >> Number of 1D 
# 2 >> Number of 0D

Array is :
 [[[2 3]
  [3 4]
  [5 6]]]
Number of dimensions are :  3
Shape of an array is : (1, 3, 2)


In [81]:
l1 = [[[2,3],[3,4],[5,6]],[[20,3],[30,4],[50,6]],[[200,3],[300,4],[500,6]]]

In [92]:
arr3 = np.array(l1)
print('Array is :\n',arr3)
print('Number of dimensions are : ',arr3.ndim)
print("Shape of an array is :",arr3.shape)
# (3,3,2)

Array is :
 [[[  2   3]
  [  3   4]
  [  5   6]]

 [[ 20   3]
  [ 30   4]
  [ 50   6]]

 [[200   3]
  [300   4]
  [500   6]]]
Number of dimensions are :  3
Shape of an array is : (3, 3, 2)


## 4-D Array

In [78]:
arr4 = np.array([[[[2,3],[3,4],[5,6]]]])
print('Array is :\n',arr4)
print('Number of dimensions are : ',arr4.ndim)

Array is :
 [[[[2 3]
   [3 4]
   [5 6]]]]
Number of dimensions are :  4


# Indexing and Slicing

In [94]:
arr1 = np.array([4,5,6,7,8])
arr1[0]

4

In [96]:
arr1[2]

6

In [98]:
arr1[-1]

8

In [104]:
arr2 = np.array([[4,5,6],[7,8,10]])
arr2[0][2]

6

In [107]:
print(arr2)

[[ 4  5  6]
 [ 7  8 10]]


In [108]:
arr2[0,1]

5

In [103]:
arr2[0,2]

6

In [109]:
arr2[1,0]

7

In [119]:
arr3 = np.array(l1)
arr3

array([[[  2,   3],
        [  3,   4],
        [  5,   6]],

       [[ 20,   3],
        [ 30,   4],
        [ 50,   6]],

       [[200,   3],
        [300,   4],
        [500,   6]]])

In [120]:
arr3[1,0,1]

3

In [114]:
arr3[2]  # 2D array

array([[200,   3],
       [300,   4],
       [500,   6]])

In [117]:
arr3[2,1,0] 

300

In [118]:
arr3[1,1,0] 

30

# Slicing

In [124]:
arr1 = np.array([4,5,6,7,8])
arr1[0:3]

array([4, 5, 6])

In [126]:
arr1 = np.array([4,5,6,7,8])
arr1[1:3]

array([5, 6])

In [129]:
arr1 = np.array([4,5,6,7,8])
arr1[::1]

array([4, 5, 6, 7, 8])

In [131]:
arr1 = np.array([4,5,6,7,8])
arr1[::-1]

array([8, 7, 6, 5, 4])

In [134]:
arr2 = np.array([[4,5,6],[7,8,9]])
arr2[0,1]

5

In [136]:
print(arr2)

[[4 5 6]
 [7 8 9]]


In [138]:
arr2[:,:]  # all rows and all columns

array([[4, 5, 6],
       [7, 8, 9]])

In [140]:
arr2[:,1]  # all rows and 1st column

array([5, 8])

In [143]:
arr2[1,:] # first row and all column

array([7, 8, 9])

In [145]:
arr2[1,:2] # first row and 0 and 1 columns

array([7, 8])

In [146]:
arr2[1,1:] # first row and 0 and 1 columns

array([8, 9])

In [152]:
arr2 = np.array([[4,5,6],[7,8,9],[10,20,30],[41,51,61],[17,18,19],[110,120,130]])
arr2[:,:]

array([[  4,   5,   6],
       [  7,   8,   9],
       [ 10,  20,  30],
       [ 41,  51,  61],
       [ 17,  18,  19],
       [110, 120, 130]])

In [153]:
arr2[:2,:2]

array([[4, 5],
       [7, 8]])

In [151]:
arr2[3:,1:]

array([[ 51,  61],
       [ 18,  19],
       [120, 130]])

In [158]:
arr2 = np.array([[4,5,6],[7,8,9],[10,20,30],[41,51,61],[17,18,19],[110,120,130]])
arr2.shape

(6, 3)

#### slicing in 3D array

In [161]:
arr3 = np.array([[[4,5,6],[7,8,9],[10,20,30]],[[41,51,61],[17,18,19],[110,120,130]]])
arr3.shape # (2,3,3)

(2, 3, 3)

In [172]:
arr3

array([[[  4,   5,   6],
        [  7,   8,   9],
        [ 10,  20,  30]],

       [[ 41,  51,  61],
        [ 17,  18,  19],
        [110, 120, 130]]])

In [177]:
arr3[:,1:,:2]

array([[[  7,   8],
        [ 10,  20]],

       [[ 17,  18],
        [110, 120]]])

In [170]:
arr3[0,1,1:]

array([8, 9])

In [171]:
arr3[0,1:,1:]

array([[ 8,  9],
       [20, 30]])

# Convert to n-D array

In [180]:
arr1 = np.array([3,4,5,6,7])
arr1.ndim

1

In [182]:
arr1 = np.array([3,4,5,6,7],ndmin = 2)
print("Array is :",arr1)
print("Number of dimensions are : ",arr1.ndim)

Array is : [[3 4 5 6 7]]
Number of dimensions are :  2


In [184]:
arr1 = np.array([3,4,5,6,7],ndmin = 3)
print("Array is :",arr1)
print("Number of dimensions are : ",arr1.ndim)

Array is : [[[3 4 5 6 7]]]
Number of dimensions are :  3


In [186]:
arr1 = np.array([3,4,5,6,7],ndmin = 4)
print("Array is :",arr1)
print("Number of dimensions are : ",arr1.ndim)

Array is : [[[[3 4 5 6 7]]]]
Number of dimensions are :  4


In [188]:
arr1 = np.array([[3,4],[5,6]],ndmin = 4)
print("Array is :",arr1)
print("Number of dimensions are : ",arr1.ndim)

Array is : [[[[3 4]
   [5 6]]]]
Number of dimensions are :  4


In [192]:
arr1 = np.array([[3,4],[5,6]],ndmin = 2)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)

Array is :
 [[3 4]
 [5 6]]
Number of dimensions are :  2


In [193]:
arr1 = np.array([[3,4],[5,6]],ndmin = 1)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)

Array is :
 [[3 4]
 [5 6]]
Number of dimensions are :  2


# Reshape Function

In [198]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

Array is :
 [ 2  3  4  5  6  7  8 10 20 30 40 50]
Number of dimensions are :  1
Shape of an array is :  (12,)


In [199]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

# arr1.reshape(rows_count,columns_count)


Array is :
 [ 2  3  4  5  6  7  8 10 20 30 40 50]
Number of dimensions are :  1
Shape of an array is :  (12,)


In [201]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])

arr1 = arr1.reshape(2,6)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

Array is :
 [[ 2  3  4  5  6  7]
 [ 8 10 20 30 40 50]]
Number of dimensions are :  2
Shape of an array is :  (2, 6)


In [203]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])

arr1 = arr1.reshape(3,4)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

Array is :
 [[ 2  3  4  5]
 [ 6  7  8 10]
 [20 30 40 50]]
Number of dimensions are :  2
Shape of an array is :  (3, 4)


In [205]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])

arr1 = arr1.reshape(4,3)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

Array is :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8 10 20]
 [30 40 50]]
Number of dimensions are :  2
Shape of an array is :  (4, 3)


In [207]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])

arr1 = arr1.reshape(6,2)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

Array is :
 [[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8 10]
 [20 30]
 [40 50]]
Number of dimensions are :  2
Shape of an array is :  (6, 2)


In [213]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])

arr1 = arr1.reshape(12,1)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

Array is :
 [[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]
 [20]
 [30]
 [40]
 [50]]
Number of dimensions are :  2
Shape of an array is :  (12, 1)


In [215]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])

arr1 = arr1.reshape(3,2,2)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

Array is :
 [[[ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8 10]]

 [[20 30]
  [40 50]]]
Number of dimensions are :  3
Shape of an array is :  (3, 2, 2)


In [217]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])

arr1 = arr1.reshape(4,1,3)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

Array is :
 [[[ 2  3  4]]

 [[ 5  6  7]]

 [[ 8 10 20]]

 [[30 40 50]]]
Number of dimensions are :  3
Shape of an array is :  (4, 1, 3)


In [219]:
arr1 = np.array([2,3,4,5,6,7,8,10,20,30,40,50])

arr1 = arr1.reshape(1,3,4)
print("Array is :\n",arr1)
print("Number of dimensions are : ",arr1.ndim)
print("Shape of an array is : ",arr1.shape)

Array is :
 [[[ 2  3  4  5]
  [ 6  7  8 10]
  [20 30 40 50]]]
Number of dimensions are :  3
Shape of an array is :  (1, 3, 4)


In [212]:
arr2= np.array([[2,3,4,5],[6,7,8,10],[20,30,40,50]])
print("Array is :\n",arr2)
print("Number of dimensions are : ",arr2.ndim)
print("Shape of an array is : ",arr2.shape)

Array is :
 [[ 2  3  4  5]
 [ 6  7  8 10]
 [20 30 40 50]]
Number of dimensions are :  2
Shape of an array is :  (3, 4)


In [225]:
arr2= np.array([[2,3,4,5],[6,7,8,10],[20,30,40,50]])
arr2 = arr2.reshape(2,3,2)

print("Array is :\n",arr2)
print("Number of dimensions are : ",arr2.ndim)
print("Shape of an array is : ",arr2.shape)

Array is :
 [[[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8 10]
  [20 30]
  [40 50]]]
Number of dimensions are :  3
Shape of an array is :  (2, 3, 2)


In [228]:
arr2= np.array([[2,3,4,5],[6,7,8,10],[20,30,40,50]])
arr2 = arr2.reshape(12)

print("Array is :\n",arr2)
print("Number of dimensions are : ",arr2.ndim)
print("Shape of an array is : ",arr2.shape)

Array is :
 [ 2  3  4  5  6  7  8 10 20 30 40 50]
Number of dimensions are :  1
Shape of an array is :  (12,)


In [231]:
l1 = list(arr2)
print(l1,type(l1))

[2, 3, 4, 5, 6, 7, 8, 10, 20, 30, 40, 50] <class 'list'>


In [235]:
l2 = arr2.tolist()
print(l2,type(l2))

[2, 3, 4, 5, 6, 7, 8, 10, 20, 30, 40, 50] <class 'list'>


In [236]:
arr2= np.array([[2,3,4,5],[6,7,8,10],[20,30,40,50]])
list2 = arr2.tolist()
print(list2,type(l2))

[2, 3, 4, 5, 6, 7, 8, 10, 20, 30, 40, 50] <class 'list'>
