# Linear Algebra

In [ ]:
3x + 4y = 15
5x + 6y = 20
x =  ? -5
y = ? 7.5

In [ ]:
AX = B
A = [[3 4
     5 6]]

X = [x y]
B = [15 20]

In [1]:
import numpy as np

In [6]:
A = np.array([[3,4], [5,6]])
print('Array is \n',A)

B = np.array([15,20])
print("Array B is \n",B)

Array is 
 [[3 4]
 [5 6]]
Array B is 
 [15 20]


In [8]:
np.linalg.inv(A)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [9]:
np.linalg.solve(A,B)

array([-5. ,  7.5])

In [11]:
A = np.array([[2,3,-5],[3,-5,7],[4,2,10]])
B = np.array([10,15,30])
np.linalg.solve(A,B)

array([5.15151515, 1.09848485, 0.71969697])