# Log 

In [1]:
import numpy as np

In [ ]:
mode >>
mean >>
median >> 

In [5]:
age = np.array([20,30,40,50,25,35])
np.mean(age)

33.333333333333336

In [9]:
age = np.array([20,300,40,50,25,35]) # 300 is outlier
np.median(age)

37.5

In [ ]:
# categorical (mode)
male
female
male
male 
NaN  >> male
female

In [ ]:
# variance >> distribution of data

In [10]:
# ((X - Xmean)^2)/N

# 20,30,40,50,25,35

# Log Function

In [12]:
np.log(10)

2.302585092994046

In [14]:
np.log(1)

0.0

In [16]:
np.log(0.2)

-1.6094379124341003

In [18]:
np.log(0.8)  # Natural log >> ln(0.8)

-0.2231435513142097

In [28]:
np.log(10)

2.302585092994046

In [29]:
np.log10(10)

1.0

In [30]:
np.log2(10)

3.321928094887362

In [26]:
np.log2([10,2,3,4,100,5,6])

array([3.32192809, 1.        , 1.5849625 , 2.        , 6.64385619,
       2.32192809, 2.5849625 ])

In [27]:
np.log([13,4,5,1,7,8,9,100,600])  # Log Transformation

array([2.56494936, 1.38629436, 1.60943791, 0.        , 1.94591015,
       2.07944154, 2.19722458, 4.60517019, 6.39692966])

# Trignometry

In [ ]:
sin >> opp/hyp
cos >> adj/hyp
tan >> opp/adj
cosec >> 1/sin
sec >> 1/cos
cot >> 1/tan



In [ ]:
sin(30) >> 1/2 >> 0.5
sin(45) >> 1/

Pi >> 180

In [32]:
# np.pi

In [34]:
np.sin(np.pi / 6)  # 180/6

0.49999999999999994

In [36]:
np.sin(np.pi / 4)  # 180/4

0.7071067811865476

In [38]:
np.sin(np.pi / 2)  # 180/4

1.0

In [40]:
np.cos(np.pi /4 )  # 180/4

0.7071067811865476

In [42]:
np.tan(np.pi/6)  # tan(30)

0.5773502691896257

# degree to radian

In [44]:
arr = np.array([0,30,45,60,90])
radian = np.deg2rad(arr)
radian

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [46]:
np.sin(0.523)

0.4994813555186418

In [48]:
np.pi/6

0.5235987755982988

# Radian to degree

In [49]:
radians = np.array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])
degree = np.rad2deg(radians)
degree

array([ 0.        , 30.00000025, 44.99999981, 59.99999993, 90.00000018])