# 1. Append()

In [ ]:
import numpy as np


In [ ]:
array1 = np.array([3,2,5,6])
array2 = np.array([10,20,30,40])

In [ ]:
np.append(array1,array2)

array([ 3,  2,  5,  6, 10, 20, 30, 40])

In [ ]:
array1 + array2

array([13, 22, 35, 46])

In [ ]:
arr = np.append(array1,100)
arr

array([  3,   2,   5,   6, 100])

In [ ]:
array1 = np.array([3,2,5,6])  # 1D
array2 = np.array([[10,20],[30,40]]) # 2D 
arr = np.append(array1,array2) # Flatten the array 
arr

array([ 3,  2,  5,  6, 10, 20, 30, 40])

In [ ]:
array1 = np.array([[3,2,5,6]])  # 1D
array2 = np.array([[10,20],[30,40]]) # 2D 
arr = np.append(array1,array2) # Flatten the array 
arr

array([ 3,  2,  5,  6, 10, 20, 30, 40])

In [ ]:
array1 = np.array([[[3,2,5,6]]])  # 3D
array2 = np.array([[10,20],[30,40]]) # 2D 
arr = np.append(array1,array2) # Flatten the array 
arr

array([ 3,  2,  5,  6, 10, 20, 30, 40])

In [ ]:
array1 = np.array([[3,2],[5,6]])  # 2D
array2 = np.array([[10,20],[30,40]]) # 2D 
print('Array1 is:\n',array1)

print('Array2 is:\n',array2)

arr = np.append(array1,array2) # Flatten the array 
arr

Array1 is:
 [[3 2]
 [5 6]]
Array2 is:
 [[10 20]
 [30 40]]


array([ 3,  2,  5,  6, 10, 20, 30, 40])

In [ ]:
array1 = np.array([[3,2],[5,6]])  # 2D
array2 = np.array([[10,20],[30,40]]) # 2D 
print('Array1 is:\n',array1)

print('Array2 is:\n',array2)

arr = np.append(array1,array2,axis = 0) # Adding Rows  
arr

Array1 is:
 [[3 2]
 [5 6]]
Array2 is:
 [[10 20]
 [30 40]]


array([[ 3,  2],
       [ 5,  6],
       [10, 20],
       [30, 40]])

In [ ]:
array1 = np.array([[3,2],[5,6]])  # 2D
array2 = np.array([[10,20],[30,40]]) # 2D 
print('Array1 is:\n',array1)

print('Array2 is:\n',array2)

arr = np.append(array1,array2,axis = 1) # Adding Rows  
arr

Array1 is:
 [[3 2]
 [5 6]]
Array2 is:
 [[10 20]
 [30 40]]


array([[ 3,  2, 10, 20],
       [ 5,  6, 30, 40]])

In [ ]:
array1 = np.array([[3,2],[5,6]])  # 2D
array2 = np.array([[10,20]]) # 2D 
print('Array1 is:\n',array1)

print('Array2 is:\n',array2)

arr = np.append(array1,array2,axis = 0) # Adding Rows  
arr

Array1 is:
 [[3 2]
 [5 6]]
Array2 is:
 [[10 20]]


array([[ 3,  2],
       [ 5,  6],
       [10, 20]])

In [ ]:
array1 = np.array([[3,2],[5,6]])  # 2D
array2 = np.array([[10,20],[1,2]]) # 2D 
print('Array1 is:\n',array1)

print('Array2 is:\n',array2)

arr = np.append(array1,array2,axis = 1) # Adding Columns  
arr

Array1 is:
 [[3 2]
 [5 6]]
Array2 is:
 [[10 20]
 [ 1  2]]


array([[ 3,  2, 10, 20],
       [ 5,  6,  1,  2]])

In [ ]:
array1 = np.array([[3,2],[5,6]])  # 2D
array2 = np.array([[10,20],[1,2]]) # 2D 
print('Array1 is:\n',array1)

print('Array2 is:\n',array2)

arr = np.append(array1,array2,axis = 1) # Adding Columns  
arr

Array1 is:
 [[3 2]
 [5 6]]
Array2 is:
 [[10 20]
 [ 1  2]]


array([[ 3,  2, 10, 20],
       [ 5,  6,  1,  2]])

# 2. concatenate()

In [ ]:
arr1 = np.array([2,3,4,5])
print('Array1 is :',arr1)

arr2 = np.array([20,30,40,50])
print('Array1 is :',arr2)

np.concatenate([arr1,arr2])

Array1 is : [2 3 4 5]
Array1 is : [20 30 40 50]


array([ 2,  3,  4,  5, 20, 30, 40, 50])

In [ ]:
arr1 = np.array([2,3,4,5])
print('Array1 is :',arr1)

arr2 = np.array([20,30,40,50])
print('Array1 is :',arr2)

arr3 = np.array([200,300,400,500])
print('Array1 is :',arr3)
np.concatenate([arr1,arr2,arr3])

Array1 is : [2 3 4 5]
Array1 is : [20 30 40 50]
Array1 is : [200 300 400 500]


array([  2,   3,   4,   5,  20,  30,  40,  50, 200, 300, 400, 500])

In [ ]:
arr1 = np.array([[2,3],[4,5]])
print('Array1 is :\n',arr1)

arr2 = np.array([[20,30],[40,50]])
print('Array1 is :\n',arr2)

result = np.concatenate([arr1,arr2])
print('Result array is :\n',result)

Array1 is :
 [[2 3]
 [4 5]]
Array1 is :
 [[20 30]
 [40 50]]
Result array is :
 [[ 2  3]
 [ 4  5]
 [20 30]
 [40 50]]


In [ ]:
arr1 = np.array([[2,3],[4,5]])
print('Array1 is :\n',arr1)

arr2 = np.array([[20,30],[40,50]])
print('Array1 is :\n',arr2)

arr3 = np.array([[200,300],[400,500]])
print('Array1 is :',arr3)

result = np.concatenate([arr1,arr2,arr3])
print('Result array is :\n',result)

Array1 is :
 [[2 3]
 [4 5]]
Array1 is :
 [[20 30]
 [40 50]]
Array1 is : [[200 300]
 [400 500]]
Result array is :
 [[  2   3]
 [  4   5]
 [ 20  30]
 [ 40  50]
 [200 300]
 [400 500]]


In [ ]:
arr1 = np.array([[2,3],[4,5]])
print('Array1 is :\n',arr1)

arr2 = np.array([[20,30],[40,50]])
print('Array1 is :\n',arr2)

arr3 = np.array([[200,300],[400,500]])
print('Array1 is :',arr3)

result = np.concatenate([arr1,arr2,arr3],axis = 1)
print('Result array is :\n',result)

Array1 is :
 [[2 3]
 [4 5]]
Array1 is :
 [[20 30]
 [40 50]]
Array1 is : [[200 300]
 [400 500]]
Result array is :
 [[  2   3  20  30 200 300]
 [  4   5  40  50 400 500]]


# For Loops 

In [ ]:
array = np.array([3,4,6,7,8,9])


In [ ]:
for i in array:
    print('value is ',i)

value is  3
value is  4
value is  6
value is  7
value is  8
value is  9


In [ ]:
arr3 = np.array([[200,300],[400,500]])
print('Array1 is :\n',arr3)

for item in arr3:
    print('value is ',item)

Array1 is :
 [[200 300]
 [400 500]]
value is  [200 300]
value is  [400 500]


In [ ]:
arr3 = np.array([[200,300],[400,500]])
print('Array1 is :\n',arr3)

for i in arr3:
    for j in i:
        print('value is ',j)

Array1 is :
 [[200 300]
 [400 500]]
value is  200
value is  300
value is  400
value is  500


In [ ]:
arr3 = np.array([[[3,4],[5,6]]])
print('Array1 is :\n',arr3)

for i in arr3:
    for j in i:
        for k in j:
            print('value is ',k)

Array1 is :
 [[[3 4]
  [5 6]]]
value is  3
value is  4
value is  5
value is  6


# nditer()

In [ ]:
arr3 = np.array([[200,300],[400,500]])
print('Array1 is :\n',arr3)

for item in np.nditer(arr3):
    print('value is ',item)

Array1 is :
 [[200 300]
 [400 500]]
value is  200
value is  300
value is  400
value is  500


In [ ]:
arr3 = np.array([[[3,4],[5,6]]])
print('Array1 is :\n',arr3)

for item in np.nditer(arr3):
    print('value is ',item)

Array1 is :
 [[[3 4]
  [5 6]]]
value is  3
value is  4
value is  5
value is  6


In [ ]:
arr3 = np.array([[200,300],[400,500]])
print('Array1 is :\n',arr3)

for i,item in np.ndenumerate(arr3):
    print(f'value at index {i} is {item}')

Array1 is :
 [[200 300]
 [400 500]]
value at index (0, 0) is 200
value at index (0, 1) is 300
value at index (1, 0) is 400
value at index (1, 1) is 500


In [ ]:
arr3 = np.array([[[3,4],[5,6]],[[30,40],[50,60]]])
print('Array1 is :\n',arr3)

for i,item in np.ndenumerate(arr3):
    print(f'value at index {i} is {item}')

Array1 is :
 [[[ 3  4]
  [ 5  6]]

 [[30 40]
  [50 60]]]
value at index (0, 0, 0) is 3
value at index (0, 0, 1) is 4
value at index (0, 1, 0) is 5
value at index (0, 1, 1) is 6
value at index (1, 0, 0) is 30
value at index (1, 0, 1) is 40
value at index (1, 1, 0) is 50
value at index (1, 1, 1) is 60


# ceil

In [ ]:

4.6 >> 5
3.5 >> 4
2.3 >> 3
4.1 >> 5

In [ ]:
np.ceil(4.6)

5.0

In [ ]:
np.ceil(2.3)

3.0

In [ ]:
np.ceil([2.1,4.5,3.4,7.8,6.9])  # [3,5,4,8,7]

array([3., 5., 4., 8., 7.])

In [ ]:
200/32 

6.25

# floor 

In [ ]:
4.6 >> 4
3.5 >> 3
2.3 >> 2
4.1 >> 4

In [ ]:
np.floor(4.6)

4.0

In [ ]:
np.floor(2.3)

2.0

In [ ]:
np.floor(2.99999)

2.0

In [ ]:
array = np.floor([2.99999,4.5,6.8,2.5]) # [2,4,6,2]
array

array([2., 4., 6., 2.])

# Around()

In [ ]:
round(3.6798,2) 

3.68

In [ ]:
round(3.6798,1) 

3.7

In [ ]:
round(3.6798) 

4

In [ ]:
np.around(3.5)

4.0

In [ ]:
np.around(3.6798)

4.0

In [ ]:
np.around(3.6798,2)

3.68

In [ ]:
array = np.around([[3.5,2],[5.6,4.9]])
array

array([[4., 2.],
       [6., 5.]])

# copy()

In [ ]:
arr1 = np.array([4,5,6,2,9])
arr1

array([4, 5, 6, 2, 9])

In [ ]:
arr2 = arr1.copy()  # deep copy
print(arr2)

In [ ]:
arr1 = np.array([[4,5],[6,2]])
arr1

array([[4, 5],
       [6, 2]])

In [ ]:
array1 = np.array([[3,2],[5,6]])  # 2D
array2 = array1.copy()  # Deep Copy
print('Array1 is:\n',array1)

print('Array2 is:\n',array2)


Array1 is:
 [[3 2]
 [5 6]]
Array2 is:
 [[3 2]
 [5 6]]


In [ ]:
array1[1,0] = 1000
array1

array([[   3,    2],
       [1000,    6]])

In [ ]:
array2

array([[3, 2],
       [5, 6]])

# np.where()

In [ ]:
l1 = [2,3,4,5,4,6,4,8,9]
l1.index(4)

indices = [i for i,item in enumerate(l1) if item == 4]
indices

[2, 4, 6]

In [ ]:
arr1 = np.array([2,3,4,5,4,6,4,8,9])

# indices = np.where(condition)
indices = np.where(arr1 == 4)
indices

(array([2, 4, 6], dtype=int64),)

In [ ]:
arr1 = np.array([2,3,4,5,4,6,4,8,9])

# indices = np.where(condition)
indices = np.where(arr1 <= 4)
indices

(array([0, 1, 2, 4, 6], dtype=int64),)

In [ ]:
# np.argmax()

In [ ]:
# dir(np)

In [ ]:
np.int32(100)

100